# Generated by Django 4.1.1 on 2023-01-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='details',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
