# Generated by Django 4.1.1 on 2023-01-26 06:12

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=500, null=True)),
                ('designation', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to=reviews.models.generate_filename)),
                ('review', models.TextField(null=True)),
            ],
        ),
    ]
