# Generated by Django 4.1.1 on 2023-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='author_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
